# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tapplyCpp <- function(tar, var, cost, nvar, ntar, n) {
    .Call(`_ImbTreeEntropy_tapplyCpp`, tar, var, cost, nvar, ntar, n)
}

EntropyCpp <- function(target, entropy_par, type) {
    .Call(`_ImbTreeEntropy_EntropyCpp`, target, entropy_par, type)
}

ClassErrorLocalCpp <- function(dat) {
    .Call(`_ImbTreeEntropy_ClassErrorLocalCpp`, dat)
}

AvoidSameClassCpp <- function(probs_l, probs_r, cost, k) {
    .Call(`_ImbTreeEntropy_AvoidSameClassCpp`, probs_l, probs_r, cost, k)
}

ProbPeak <- function(prob, ntar) {
    .Call(`_ImbTreeEntropy_ProbPeak`, prob, ntar)
}

InformationGainCpp <- function(variable, n, target, ntar, entropy_parent, entropy_par, cp, type, weights, cost, overfit) {
    .Call(`_ImbTreeEntropy_InformationGainCpp`, variable, n, target, ntar, entropy_parent, entropy_par, cp, type, weights, cost, overfit)
}

